
ansible_user: <add_local_user>
pkg_manager: "{{ 'apt' if ansible_facts['os_family'] == 'Debian' else 'yum' }}"
debian_ubuntu_packages:
  - sudo
  - vim
  - htop
  - screen
  - net-tools
  - git
  - cifs-utils
  - gnupg
  - curl
  - gcc
  - mlocate
  - lsof
  - netcat-openbsd


