---
# Configure journald for max 500MB and 2-week retention

- name: Ensure journald.conf.d exists
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Deploy journald drop-in for security_setup limits
  ansible.builtin.template:
    src: journald-security_setup.conf.j2
    dest: /etc/systemd/journald.conf.d/security_setup.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Restart journald to apply limits
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
  become: yes
  ignore_errors: yes  # may not have permission or service might not allow restart
