---
# Linux (Debian, RHEL): nftables firewall with input/output filtering and logging

- name: Disable and mask firewalld (RHEL) so nftables is the only firewall
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
    masked: true
  become: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install nftables (Debian/Ubuntu)
  ansible.builtin.package:
    name: nftables
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Install nftables (RHEL)
  ansible.builtin.package:
    name: nftables
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: Deploy nftables rules file
  ansible.builtin.template:
    src: nftables-filter.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0600'
  become: yes

- name: Flush and load nftables rules (may temporarily interrupt SSH connection)
  ansible.builtin.shell: "nft -f /etc/nftables.conf; echo 'nftables rules loaded'"
  become: yes
  changed_when: true
  register: nft_result
  async: 15
  poll: 3
  # Note: If SSH connection drops due to rule reload, Ansible will reconnect
  # The rules should allow SSH from control host's subnet, so reconnection will work

- name: Enable and start nftables service (Debian)
  ansible.builtin.systemd:
    name: nftables
    state: started
    enabled: true
  become: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Enable and start nftables service (RHEL)
  ansible.builtin.systemd:
    name: nftables
    state: started
    enabled: true
  become: yes
  when: ansible_facts['os_family'] == 'RedHat'
